clc
clear
close all

%% =========================================================
% PUBLICATION FIGURE
% Parametric robustness with respect to A1
%
% Panel (a): Regulation of x13
% Panel (b): Observer output-estimation error
% ==========================================================

load('symbolic_A1_robustness_results.mat', ...
    'A1_values', ...
    't_save', ...
    'x13_save', ...
    'output_est_err_save');

%% Settings
t_ctrl = 5;
epsilon = 1e-3;

%% =========================================================
% Figure
% ==========================================================
fig = figure( ...
    'Color','w', ...
    'Units','centimeters', ...
    'Position',[2 2 17.5 12]);

tl = tiledlayout(2,1, ...
    'TileSpacing','compact', ...
    'Padding','compact');

%% =========================================================
% (a) Regulation of x13
% ==========================================================
ax1 = nexttile;
hold(ax1,'on');

for k = 1:length(A1_values)

    plot( ...
        t_save{k}, ...
        x13_save{k}, ...
        'LineWidth',1.15);

end

%% Reference
yline( ...
    epsilon, ...
    '--', ...
    'LineWidth',1.0);

%% Controller activation
xline( ...
    t_ctrl, ...
    '--', ...
    'LineWidth',1.0);

ylabel( ...
    '$x_{13}$', ...
    'Interpreter','latex', ...
    'FontSize',11);

text( ...
    0.015,0.90,'(a)', ...
    'Units','normalized', ...
    'FontWeight','bold', ...
    'FontSize',10);

grid on
box on

set(ax1, ...
    'FontName','Times New Roman', ...
    'FontSize',9, ...
    'LineWidth',0.8);

%% Legend
legend( ...
    '$A_1=6.5$', ...
    '$A_1=7.0$', ...
    '$A_1=7.5$', ...
    '$\varepsilon=10^{-3}$', ...
    'Interpreter','latex', ...
    'Location','northeast', ...
    'Box','off');

%% Controller label
yl1 = ylim(ax1);

text( ...
    t_ctrl+0.15, ...
    yl1(2)-0.08*(yl1(2)-yl1(1)), ...
    'Controller ON', ...
    'FontName','Times New Roman', ...
    'FontSize',8);

%% =========================================================
% (b) Observer output-estimation error
% ==========================================================
ax2 = nexttile;
hold(ax2,'on');

for k = 1:length(A1_values)

    plot( ...
        t_save{k}, ...
        output_est_err_save{k}, ...
        'LineWidth',1.05);

end

%% Zero-error reference
yline( ...
    0, ...
    '--', ...
    'LineWidth',0.9);

%% Controller activation
xline( ...
    t_ctrl, ...
    '--', ...
    'LineWidth',1.0);

xlabel( ...
    'Time (s)', ...
    'FontName','Times New Roman', ...
    'FontSize',10);

ylabel( ...
    '$\tilde{y}=\hat{y}_m-y_m$ (mV)', ...
    'Interpreter','latex', ...
    'FontSize',10);

text( ...
    0.015,0.90,'(b)', ...
    'Units','normalized', ...
    'FontWeight','bold', ...
    'FontSize',10);

grid on
box on

set(ax2, ...
    'FontName','Times New Roman', ...
    'FontSize',9, ...
    'LineWidth',0.8);

legend( ...
    '$A_1=6.5$', ...
    '$A_1=7.0$', ...
    '$A_1=7.5$', ...
    'Interpreter','latex', ...
    'Location','northeast', ...
    'Box','off');

%% =========================================================
% Common time axis
% ==========================================================
linkaxes([ax1 ax2],'x');

xlim([0 10]);

%% =========================================================
% Export
% ==========================================================
exportgraphics( ...
    fig, ...
    'symbolic_A1_robustness_observer.pdf', ...
    'ContentType','vector');

exportgraphics( ...
    fig, ...
    'symbolic_A1_robustness_observer.png', ...
    'Resolution',600);

fprintf('\nFigure saved as:\n');
fprintf('symbolic_A1_robustness_observer.pdf\n');
fprintf('symbolic_A1_robustness_observer.png\n');